apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: denormalization
spec:
  encryptedData:
    db: AgBOEvIk/yC9/PteBmSk4VCwLu0PfNFvtvwwTBect7CQ2/GjNjO99e5PLZXzrRKPcYB6A0J/DnQoFSlMHgV1lBDcx8TL7B/449sXSoBLwe3TeqLV5hlGEI5IGyeqbsVrmhKXPr7kJ5L33m/OFf+jvBpm5JeDCVh9Us40hlaIJDfUV9pTNzxU3HxuotEKIci8qzvy0O20+rk0YVk+xZ2951e89mrbz3JDCxS5KDpnciiC9Yvoe1PrjjPPrANvYHfAghO5VsjGisn3NnDpc8mvPLspNMgaBWhpxyCTUDxKKa+df9UOw0unxAGeuIvjjRhiUDSLKyhMimcP8vrSUtmDrklu0W+1pMZoylb5A8Jr6RMjPdfijbs6kC2TPfvpqa4jtlijJps44AtqcItxEzJUzMvo9a6r4bH5CtI467qf+W9ySxVA+AuYiqP6mCaAvL+xDnEz3YHVKYDmyHqBg4FDtlGEiEneeniumSKeDirJTgfD2eQyw8tA16EC3ZGlQMYP/DJFWLtJLZ0ufEHud84J3rg6wSmBMBWWcMcvlkgXJlpX2Hw5SE0NDqBiyzXPjw6geyUYHqMYzhWX88BdmhJWNIM+Rz5qBANQibEUVOUHg/N2IqhB82BsS0YZ7VanLnJyeAY7PUY0OOKllwSgPnoB5Cg5W0X5W5ekM0pDgL5sEPYRABU+46cg8nIeoeiusrNuiSj7/HHdDYdWbkNXaB5JrLyB1dqnf7EhhOUlrm4Fx0Fn3q8Afi67KsN73H/rHRqumgYhiWjc3s9VBlSbBSZg+b/r3Jjk3WgOVQmlvQUDX+j+e/7UG7uYdRelnoapEcRiA8zqu6vDO/KONeHqDtcw4NLm3iz+wyQsZ3yFQQdfDOUUzezvx2KKDiUI/fqmM/ibZrr6dsk=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: denormalization

